// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnbudtwftqixttpecpso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBuYnVkdHdmdHFpeHR0cGVjcHNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1NjM2MzksImV4cCI6MjA1NjEzOTYzOX0.PwL6v2ETgtYVlsm5-X51TGGtCbY8eDXDUgrceUw34s0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);